Repository Bahartaskin/Group6_Project1_WeAreAwesome, pull requests merged in 2022-12, with the labels that each got.

#13 matt_branch2_Answer1 posted on .java class named as Matt1
  src/files/Matt1.java
Labels: enhancement, good first issue

#24 updated matt1 java class for matt_branch3
  src/files/Matt1.java
Labels: bug, documentation, invalid, question

#33 Pull request for Gokhan_branch6
  src/files/GitHubGitCheatSheet.html
Labels: help wanted, question

#34 Gokhan_Branch5 Pull request
  src/files/NumbersToArray.java
Labels: bug, duplicate, good first issue, invalid
